[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "~/.config/sesh/scripts/nvim.sh"

[[session]]
name = "keyboards"
path = "~/src/keyboards"

[[session]]
name = "v2"
path = "~/src/v2"
startup_command = "~/.config/sesh/scripts/symfony.sh"


