gui:
  language: 'en'
  theme:
    activeBordercolor:
      - '#34302c'
      - bold
    inactiveBordercolor:
      - '#bd8183'
    optionsTextColor:
      - '#89b4f4'
    selectedLineBgColor:
      - '#ece1d7'
    selectedRangeBgColor:
      - '#ece1d7'
    cherryPickedCommitBgColor:
      - '#403a46'
    cherryPickedCommitFgColor:
      - '#403a46'
    unstagedChangesColor:
      - '#e49b5d'
    defaultFgColor:
      - '#ece1d7'


