[tools]
#zoxide = "0.9.4"
nodejs = "22"
#ruby = "3.3.0"
#sqlite = "3.45.2"
#php = "8.3.4"
#stylua = "0.20.0"
#neovim = "0.9.5"
jq = "1.7.1"
jqp = "0.5.0"
go = "1.24.7"
#python = "3.12.3"
#tmux = "latest"
zellij = "latest"
python = "3.12"
ubi = "latest"
shfmt = "latest"
yarn = "latest"
lua-language-server = "latest"
lua = "5.1"
pnpm = "latest"

#"go:github.com/joshmedeski/sesh" = "latest"
