gui:
  language: 'en'
  theme:
    activeBorderColor:
      - '#928374'
      - bold
    inactiveBorderColor:
      - '#504945'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#665c54'
    cherryPickedCommitBgColor:
      - '#504945'
    cherryPickedCommitFgColor:
      - '#d5c4a1'
    unstagedChangesColor:
      - '#d79921'
    defaultFgColor:
      - '#ebdbb2'
    searchingActiveBorderColor:
      - '#f9e2af'
  authorColors:
    '*': '#b8bb26'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --syntax-theme=gruvbox-dark
