-- icons we will use, defined in one place for easier overrides
return {
	lsp = {
		diagnostic = {
			signs = {
				Ok = "󰄳",
				Error = "󰅚",
				Warn = "󰀦",
				Info = "󰋼",
				Hint = "󰛨",
			},
			upper_signs = {
				-- We don't want to calculate these on the fly.
				OK = "󰄳",
				ERROR = "󰅚",
				WARN = "󰀦",
				INFO = "󰋼",
				HINT = "󰛨",
			},
		},
	},

	kinds = {
		Array = " ",
		Boolean = "󰨙 ",
		Class = " ",
		Codeium = "󰘦 ",
		Color = " ",
		Control = " ",
		Collapsed = " ",
		Constant = "󰏿 ",
		Constructor = " ",
		Copilot = " ",
		Enum = " ",
		EnumMember = " ",
		Event = " ",
		Field = " ",
		File = " ",
		Folder = " ",
		Function = "󰊕 ",
		Git = "󰊢",
		Interface = " ",
		Key = " ",
		Keyword = " ",
		Method = "󰊕 ",
		Module = " ",
		Namespace = "󰦮 ",
		Null = " ",
		Number = "󰎠 ",
		Object = " ",
		Operator = " ",
		Package = " ",
		Property = " ",
		Reference = " ",
		Server = "󰒋",
		Snippet = " ",
		String = " ",
		Struct = "󰆼 ",
		TabNine = "󰏚 ",
		Text = " ",
		TypeParameter = " ",
		Unit = " ",
		Value = " ",
		Variable = "󰀫 ",
	},

	border_fn = function(hl)
		return {
			{ "╭", hl },
			{ "─", hl },
			{ "╮", hl },
			{ "│", hl },
			{ "╯", hl },
			{ "─", hl },
			{ "╰", hl },
			{ "│", hl },
		}
	end,
}
