#!/usr/bin/env sh

# do this only if SIP is patched
#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
#sudo yabai --load-sa

yabai -m config window_gap                    2

yabai -m config layout                        bsp
yabai -m config focus_follows_mouse           off
yabai -m config mouse_follows_focus           off
yabai -m config window_placement              second_child
yabai -m config window_shadow                 off
yabai -m config window_topmost                off 
yabai -m config window_origin_display         focused
yabai -m config split_ratio                   0.50
yabai -m config auto_balance                  on
yabai -m config mouse_modifer                 ctrl
yabai -m config mouse_action1                 move
yabai -m config mouse_action2                 resize

yabai -m config --space 6 layout float

# general space settings
yabai -m config external_bar all:26:0
#yabai -m config top_padding 25
#yabai -m config botton_padding 25
#yabai -m config left_padding 25
#yabai -m config right_padding 25
#yabai -m config window_gap 20
#yabai -m config top_padding 34

yabai -m rule --add app="Garmin Express"        manage=off
yabai -m rule --add app="Microsoft Defender"    manage=off
yabai -m rule --add app="Company Portal"        manage=off
yabai -m rule --add app="System Settings"       manage=off
yabai -m rule --add app="System Preferences"    manage=off
yabai -m rule --add app="App Store"             manage=off
yabai -m rule --add app="Activity Monitor"      manage=off
yabai -m rule --add app="Preview"               manage=off
yabai -m rule --add app="zoom.us"               manage=off
yabai -m rule --add app="Transmission"          manage=off
yabai -m rule --add app="Fantastical"           manage=off
yabai -m rule --add title="popup"               manage=off

# global settings
# focus window that your mouse hovers on (disabled due to right click bugs)

# move mouse to focused window
# floating windows always stay on top
# enable borders
#yabai -m config window_border                on
# no clue what this is
#yabai -m config insert_feedback_color        0xffd75f5f
#yabai -m config split_ratio                  0.50
# don't automatically rebalance windows
# swap windows if moved with mouse
#yabai -m config mouse_action1                move
# resize windows if resized with mouse
#yabai -m config mouse_action2                resize
#yabai -m config mouse_drop_action            swap

# general space settings
#yabai -m config layout                       bsp
#yabai -m config top_padding                  1
#yabai -m config bottom_padding               1
#yabai -m config left_padding                 1
#yabai -m config right_padding                1
#yabai -m config window_gap                   03

# SIP Required
# prevent border from being under the active window
#yabai -m config active_window_border_topmost on
#yabai -m config window_shadow                on
#yabai -m config window_opacity               off
#yabai -m config window_border_width          6
#yabai -m config active_window_border_color   0xffff3050
#yabai -m config normal_window_border_color   0xffaaaaaa

yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-index-jsx\"'"

